server:
  port: 8084

spring:
  cloud:
    gateway:
      globalcors:
       add-to-simple-url-handler-mapping: true
       cors-configurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:4200"
            - "http://localhost:4200/login"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
          allowedHeaders:
            - "*"
          allowCredentials: true
          maxAge: 3600
      routes:
        - id: simcard-app
          uri: lb://SIMCARD-SERVICE
          predicates:
            - Path=/simCard/**
          # filters:
          #   - AuthenticationFilter

        - id: auth-app
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/client/auth/**

        - id: payment-app
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: plan-app
          uri: lb://PLAN-SERVICE
          predicates:
            - Path=/api/plans/**

        - id: validation-app
          uri: lb://VALIDATIONN-SERVICE
          predicates:
            - Path=/mobileNumber/**

  application:
    name: SERVICE-GATEWAY

    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
